export type TravelMode = "flight" | "train";

export type Trip = {
  id: string;
  mode: TravelMode;
  operator: string;
  code: string;
  logo: string;
  from: string;
  fromCode: string;
  to: string;
  toCode: string;
  depart: string;
  arrive: string;
  durationMin: number;
  stops: number;
  price: number;
  travelClass: string;
  rating: number;
};

export const CITIES = [
  { name: "Delhi", code: "DEL" },
  { name: "Mumbai", code: "BOM" },
  { name: "Bengaluru", code: "BLR" },
  { name: "Goa", code: "GOI" },
  { name: "Jaipur", code: "JAI" },
  { name: "Kolkata", code: "CCU" },
  { name: "Chennai", code: "MAA" },
  { name: "Hyderabad", code: "HYD" },
];

export const FLIGHT_CLASSES = ["Economy", "Business", "First"] as const;
export const TRAIN_CLASSES = ["Sleeper", "AC", "General"] as const;

export const FLIGHTS: Trip[] = [
  {
    id: "f1",
    mode: "flight",
    operator: "IndiGo",
    code: "6E-2043",
    logo: "6E",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "06:15",
    arrive: "08:25",
    durationMin: 130,
    stops: 0,
    price: 4299,
    travelClass: "Economy",
    rating: 4.3,
  },
  {
    id: "f2",
    mode: "flight",
    operator: "Air India",
    code: "AI-806",
    logo: "AI",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "09:40",
    arrive: "11:55",
    durationMin: 135,
    stops: 0,
    price: 5150,
    travelClass: "Economy",
    rating: 4.0,
  },
  {
    id: "f3",
    mode: "flight",
    operator: "Vistara",
    code: "UK-995",
    logo: "UK",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "12:10",
    arrive: "14:30",
    durationMin: 140,
    stops: 0,
    price: 6320,
    travelClass: "Business",
    rating: 4.6,
  },
  {
    id: "f4",
    mode: "flight",
    operator: "SpiceJet",
    code: "SG-8194",
    logo: "SG",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "15:05",
    arrive: "18:45",
    durationMin: 220,
    stops: 1,
    price: 3890,
    travelClass: "Economy",
    rating: 3.8,
  },
  {
    id: "f5",
    mode: "flight",
    operator: "Akasa Air",
    code: "QP-1374",
    logo: "QP",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "17:35",
    arrive: "19:50",
    durationMin: 135,
    stops: 0,
    price: 4720,
    travelClass: "Economy",
    rating: 4.4,
  },
  {
    id: "f6",
    mode: "flight",
    operator: "IndiGo",
    code: "6E-5501",
    logo: "6E",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "19:20",
    arrive: "23:15",
    durationMin: 235,
    stops: 1,
    price: 3650,
    travelClass: "Economy",
    rating: 4.1,
  },
  {
    id: "f7",
    mode: "flight",
    operator: "Vistara",
    code: "UK-772",
    logo: "UK",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "21:00",
    arrive: "23:10",
    durationMin: 130,
    stops: 0,
    price: 5890,
    travelClass: "Economy",
    rating: 4.5,
  },
  {
    id: "f8",
    mode: "flight",
    operator: "Air India",
    code: "AI-2974",
    logo: "AI",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "23:45",
    arrive: "02:05",
    durationMin: 140,
    stops: 0,
    price: 4480,
    travelClass: "Economy",
    rating: 3.9,
  },
  {
    id: "f9",
    mode: "flight",
    operator: "SpiceJet",
    code: "SG-476",
    logo: "SG",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "05:20",
    arrive: "07:40",
    durationMin: 140,
    stops: 0,
    price: 4120,
    travelClass: "Economy",
    rating: 3.7,
  },
  {
    id: "f10",
    mode: "flight",
    operator: "Akasa Air",
    code: "QP-1180",
    logo: "QP",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "13:55",
    arrive: "18:20",
    durationMin: 265,
    stops: 2,
    price: 3320,
    travelClass: "Economy",
    rating: 4.0,
  },
];

export const TRAINS: Trip[] = [
  {
    id: "t1",
    mode: "train",
    operator: "Rajdhani Express",
    code: "12951",
    logo: "RJ",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "BCT",
    depart: "16:25",
    arrive: "08:35",
    durationMin: 970,
    stops: 5,
    price: 2450,
    travelClass: "AC",
    rating: 4.5,
  },
  {
    id: "t2",
    mode: "train",
    operator: "August Kranti Rajdhani",
    code: "12953",
    logo: "AK",
    from: "Delhi",
    fromCode: "NZM",
    to: "Mumbai",
    toCode: "BCT",
    depart: "17:10",
    arrive: "09:55",
    durationMin: 1005,
    stops: 6,
    price: 2280,
    travelClass: "AC",
    rating: 4.2,
  },
  {
    id: "t3",
    mode: "train",
    operator: "Paschim Express",
    code: "12925",
    logo: "PX",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "BDTS",
    depart: "11:25",
    arrive: "12:40",
    durationMin: 1515,
    stops: 18,
    price: 860,
    travelClass: "Sleeper",
    rating: 3.6,
  },
  {
    id: "t4",
    mode: "train",
    operator: "Golden Temple Mail",
    code: "12904",
    logo: "GT",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "BCT",
    depart: "07:20",
    arrive: "10:05",
    durationMin: 1605,
    stops: 21,
    price: 720,
    travelClass: "Sleeper",
    rating: 3.4,
  },
  {
    id: "t5",
    mode: "train",
    operator: "Mumbai Duronto",
    code: "12262",
    logo: "DR",
    from: "Delhi",
    fromCode: "NZM",
    to: "Mumbai",
    toCode: "BCT",
    depart: "23:00",
    arrive: "15:45",
    durationMin: 1005,
    stops: 3,
    price: 2610,
    travelClass: "AC",
    rating: 4.4,
  },
  {
    id: "t6",
    mode: "train",
    operator: "Punjab Mail",
    code: "12138",
    logo: "PM",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "CSMT",
    depart: "05:15",
    arrive: "09:20",
    durationMin: 1685,
    stops: 24,
    price: 640,
    travelClass: "General",
    rating: 3.2,
  },
  {
    id: "t7",
    mode: "train",
    operator: "Garib Rath",
    code: "12909",
    logo: "GR",
    from: "Delhi",
    fromCode: "NZM",
    to: "Mumbai",
    toCode: "BDTS",
    depart: "15:35",
    arrive: "10:15",
    durationMin: 1120,
    stops: 9,
    price: 1180,
    travelClass: "AC",
    rating: 3.9,
  },
  {
    id: "t8",
    mode: "train",
    operator: "Swaraj Express",
    code: "12471",
    logo: "SW",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "BDTS",
    depart: "09:45",
    arrive: "13:30",
    durationMin: 1665,
    stops: 22,
    price: 780,
    travelClass: "Sleeper",
    rating: 3.5,
  },
  {
    id: "t9",
    mode: "train",
    operator: "Tejas Rajdhani",
    code: "12957",
    logo: "TJ",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "BCT",
    depart: "19:55",
    arrive: "12:10",
    durationMin: 975,
    stops: 4,
    price: 2890,
    travelClass: "AC",
    rating: 4.7,
  },
  {
    id: "t10",
    mode: "train",
    operator: "Avadh Express",
    code: "19039",
    logo: "AV",
    from: "Delhi",
    fromCode: "NDLS",
    to: "Mumbai",
    toCode: "BDTS",
    depart: "21:40",
    arrive: "06:55",
    durationMin: 1755,
    stops: 26,
    price: 590,
    travelClass: "General",
    rating: 3.1,
  },
];

export type BookingStatus = "Confirmed" | "Cancelled" | "Completed";

export type Booking = {
  ref: string;
  trip: Trip;
  date: string;
  passengers: { name: string; age: string; gender: string }[];
  seats: string[];
  total: number;
  status: BookingStatus;
};

export const SEED_BOOKINGS: Booking[] = [
  {
    ref: "WF7TK42Q",
    trip: FLIGHTS[2]!,
    date: "2026-10-14",
    passengers: [{ name: "Rudraksh Samal", age: "28", gender: "Male" }],
    seats: ["12A"],
    total: 7183,
    status: "Confirmed",
  },
  {
    ref: "WF3MD90X",
    trip: TRAINS[0]!,
    date: "2026-11-02",
    passengers: [
      { name: "Rudraksh Samal", age: "28", gender: "Male" },
      { name: "Ananya Rao", age: "26", gender: "Female" },
    ],
    seats: ["B2-14", "B2-15"],
    total: 5390,
    status: "Confirmed",
  },
  {
    ref: "WF1QA55L",
    trip: FLIGHTS[0]!,
    date: "2026-08-08",
    passengers: [{ name: "Rudraksh Samal", age: "28", gender: "Male" }],
    seats: ["7C"],
    total: 4899,
    status: "Completed",
  },
  {
    ref: "WF8ZP11B",
    trip: TRAINS[4]!,
    date: "2026-07-19",
    passengers: [{ name: "Rudraksh Samal", age: "28", gender: "Male" }],
    seats: ["A1-08"],
    total: 2940,
    status: "Cancelled",
  },
];

export function formatDuration(min: number) {
  const h = Math.floor(min / 60);
  const m = min % 60;
  return `${h}h ${m.toString().padStart(2, "0")}m`;
}

export function inr(value: number) {
  return `₹${value.toLocaleString("en-IN")}`;
}

export function fareBreakdown(base: number, passengers: number) {
  const fare = base * passengers;
  const taxes = Math.round(fare * 0.12);
  const convenience = 199 * passengers;
  return { fare, taxes, convenience, total: fare + taxes + convenience };
}
